site_name: components/cert-manager
site_url: https://platform.karavel.io/components/cert-manager
repo_name: karavel-io/platform-component-cert-manager
repo_url: https://github.com/karavel-io/platform-component-cert-manager
copyright: © 2022 The Karavel Project | Documentation distributed under CC BY SA 4.0
strict: false
theme:
  name: material
  palette:
    scheme: slate
markdown_extensions:
  - meta
  - footnotes
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.superfences
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
nav:
  - Overview: index.md
  - 1.0.0:
    - 1.0.0/configuration.md
