{{- if .Values.letsencrypt.cloudflare.enable }}
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ include "cert-manager.name" . }}-cloudflare-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cert-manager.name" . }}-cloudflare-secret
    {{- include "cert-manager.labels" . | nindent 4 }}
spec:
  {{- with required "param letsencrypt.cloudflare.secret is required for generating cert-manager-cloudflare-secret" .Values.letsencrypt.cloudflare.secret }}
  backendType: {{ .backend }}
  data:
    - name: cf-api-token
      key: {{ .key }}
      property: {{ .property }}
  {{- end }}
{{- end }}
---
  {{- if .Values.letsencrypt.cloudflare.enable }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "cert-manager.name" . }}-cloudflare-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cert-manager.name" . }}-cloudflare-secret
  {{- include "cert-manager.labels" . | nindent 4 }}
spec:
  {{- with required "param letsencrypt.cloudflare.secret is required for generating cert-manager-cloudflare-secret" .Values.letsencrypt.cloudflare.secret }}
  secretStoreRef:
    name: {{ .store.name }}
    kind: {{ .store.kind }}
  target:
    creationPolicy: 'Owner'
  data:
    - secretKey: cf-api-token
      remoteRef:
        key: {{ .key }}
        property: {{ .property }}
{{- end }}
{{- end }}
