apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "cert-manager.name" . }}-webhook
  labels:
    app.kubernetes.io/name: {{ include "cert-manager.name" . }}-webhook
    {{- include "cert-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
  annotations:
    cert-manager.io/inject-ca-from-secret: "{{ .Release.Namespace }}/{{ include "cert-manager.name" . }}-webhook-ca"
webhooks:
  - name: webhook.cert-manager.io
    rules:
      - apiGroups:
          - "cert-manager.io"
          - "acme.cert-manager.io"
        apiVersions:
          - "*"
        operations:
          - CREATE
          - UPDATE
        resources:
          - "*/*"
    admissionReviewVersions: ["v1"]
    matchPolicy: Equivalent
    timeoutSeconds: 10
    failurePolicy: Fail
    sideEffects: None
    clientConfig:
      service:
        name: {{ include "cert-manager.name" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: /mutate
